config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'games#index'
  resources :games do
    resources :pawns
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  ### CALLBACKS ###
  before_create :set_default

  ### RELATIONS ###
  has_many :pawns, dependent: :destroy

  def set_default
    self.join_deadline =  (Time.now + 60)
    self.next_round = (Time.now + 60)
    self.round_number = 0
  end
end

app/models/pawn.rb
class Pawn < ActiveRecord::Base
  ### RELATIONS ###
  belongs_to :user
  belongs_to :game

  ### VALIDATIONS ###
  validates :color, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :recoverable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  ### VALIDATIONS ###
  has_many :pawns
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_game, only: [:show]
  before_action :progress_games
  

  def index
    @games = Game.all
  end

  def show
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to @game
    else
      render :new
    end
  end

  private
    def progress_games
      Game.all.each do |game|
        if game.next_round < Time.now
          game.round_number= (game.round_number + 1)
        end 

        if game.round_number == 3
          redirect_to root_path, notice: 'Game afgelopen'
          game.destroy
        elsif game.next_round < Time.now
          game.next_round = (game.next_round + 60)
          game.save
        end
      end
    end

    def set_game
      @game = Game.find(params[:id])
    end

    def game_params
      params.require(:game).permit(:title)
    end
end

app/controllers/pawns_controller.rb
class PawnsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pawn, only: [:show]
  before_action :set_game, only: [:new, :create]

  def show
  end

  def new
    @pawn = Pawn.new
  end

  def create
    @pawn = Pawn.new(pawn_params)
    @pawn.user = current_user
    @pawn.game = @game
    if @pawn.save
      redirect_to @game
    else
      redirect_to @game
    end
  end

  private
    def pawn_params
      params.require(:pawn).permit(:color)
    end

    def set_pawn
      @pawn = Pawn.find(params[:id])
    end

    def set_game
      @game = Game.find(params[:game_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<h1>Games</h1>

<%= link_to 'Game aanmaken', new_game_path %>

<% @games.each do |game| %>
  <%= link_to game do %>
    <p>Game nr: #<%= game.id %> <%= game.title %> <%= game.round_number %></p>
  <% end %>
<% end %>

app/views/games/new.html.erb
<%= form_for @game do |f| %>
  <%= f.text_field :title, placeholder: 'titel' %>
  <%= f.submit %>
<% end %>

app/views/games/show.html.erb
<h1>Game nr: #<%= @game.id %> <%= @game.title %></h1>

<h2>
  <% if @game.join_deadline > Time.now %>
    Je hebt nog : <span id='join_deadline'><%= '%.0f' % ((@game.join_deadline + 1) - Time.now)%></span> seconden om mee te doen!
  <% else %>
    Ronde <%= @game.round_number %> Volgende ronde in: <span id='next_round'><%= '%.0f' % ((@game.next_round + 1) - Time.now)%></span>
  <% end %>
</h2>

<script type="text/javascript">
  var join_deadline = <%= '%.0f' % ((@game.join_deadline + 1) - Time.now)%>
  setInterval( function() {
      join_deadline--;
      $('#join_deadline').html(join_deadline);
      if (join_deadline === 0) {
          location.reload();
      }    
  }, 1000 );

  var next_round = <%= '%.0f' % ((@game.next_round + 1) - Time.now)%>
  setInterval( function() {
      next_round--;
      $('#next_round').html(next_round);
      if (next_round === 0) {
          location.reload();
      }    
  }, 1000 );
</script>

<%= link_to 'Meedoen', new_game_pawn_path(@game) if @game.join_deadline > Time.now %>

<% @game.pawns.each do |pawn| %>
  <div class='pawn', style="background:<%= pawn.color %>"></div>
  <p><%= pawn.user.email %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tabletop</title>
    <meta name='viewport' content='width=device-width, initial-scale=1, user-scalable=no'/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= notice %>
    <%= yield %>

  </body>
</html>

app/views/pawns/_form.html.erb
<%= form_for [@game, @pawn] do |f| %>
  <%= f.color_field :color %>
  <%= f.submit %>
<% end %>

app/views/pawns/new.html.erb
<%= render 'form' %>